yolo_model:

  config_file:
    name: yolov3-tiny-light.cfg
  weight_file:
    name: yolov3-tiny-light_last.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - red
      - green
      - yellow

     
