yolo_model:

  config_file:
    name: yolov3-tiny-blocks.cfg
  weight_file:
    name: yolov3-tiny-blocks_last.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - block_A
      - block_B
      - block_C
      - block_D
      - sign_A
      - sign_B
      - sign_C
      - sign_D
      - stop

     
