/octomap_server:
  ros__parameters:
    base_frame_id: camera_link
    color:
      a: 1.0
      b: 1.0
      g: 0.0
      r: 0.0
    color_factor: 0.8
    color_free:
      a: 1.0
      b: 0.0
      g: 1.0
      r: 0.0
    colored_map: false
    compress_map: true
    filter_ground_plane: false
    filter_speckles: false
    frame_id: map
    ground_filter:
      angle: 0.15
      distance: 0.04
      plane_distance: 0.07
    incremental_2D_projection: false
    latch: true
    max_depth: 16
    min_x_size: 0.0
    min_y_size: 0.0
    occupancy_max_z: 100.0
    occupancy_min_z: -100.0
    octomap_path: ''
    point_cloud_max_x: 1.7976931348623157e+308
    point_cloud_max_y: 1.7976931348623157e+308
    point_cloud_max_z: 100.0
    point_cloud_min_x: -1.7976931348623157e+308
    point_cloud_min_y: -1.7976931348623157e+308
    point_cloud_min_z: -100.0
    publish_free_space: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    resolution: 0.05
    sensor_model:
      hit: 0.7
      max: 0.97
      max_range: -1.0
      min: 0.12
      miss: 0.4
    use_height_map: false
    use_sim_time: false
