/lslidar_driver_node:
  ros__parameters: 
    frame_id: laser                                         #激光坐标
    group_ip: 224.1.1.2
    add_multicast: false 
    device_ip: 192.168.1.200                                #雷达目的ip
    device_ip_difop: 192.168.1.102                          #雷达源IP
    msop_port: 2368                                         #雷达目的端口号
    difop_port: 2369                                        #雷达源端口号
    lidar_name: M10                                         #雷达选择:M10 M10_P M10_PLUS M10_GPS N10
    ceil_increase: -1                                        #Lsm10*时改值应设置为-1
    angle_disable_min: 0.0                                  #单角度裁剪开始值（使用多角度裁剪时应设为0）
    angle_disable_max: 0.0                                  #单角度裁剪结束值（使用多角度裁剪时应设为0）
    
    # 多角度裁剪功能
    truncated_mode_: 1                                      #多角度裁剪开关：0=关闭, 1=开启
    scan_crop_min: [10.0, 50.0, 135.0]                     #多角度裁剪起始角度列表（度）
    scan_crop_max: [30.0, 60.0, 225.0]                     #多角度裁剪结束角度列表（度）
                                                            #示例：屏蔽10°-30°, 50°-60°, 135°-225°三个角度范围
    
    min_range: 0.0                                          #雷达接收距离最小值
    max_range: 200.0                                        #雷达接收距离最大值
    use_gps_ts: false                                       #雷达是否使用GPS授时
    scan_topic: /scan                                       #设置激光数据topic名称
    interface_selection: net                                #接口选择:net 为网口,serial 为串口。
    serial_port_: /dev/wheeltec_lidar                       #串口连接时的串口号
#    pcap: /home/ls/work/2211/M10_P_gps.pcap                 #雷达是否使用pcap包读取功能
